routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['locale']], function(){
  Route::get('/', 'HomeController@index')->name('home');
  Route::get('/advertise', 'AdvertController@index')->name('advertise');
  Route::get('/metodology', 'MetodologyController@show')->name('metodology');
  Route::get('/ico-ratings', 'RatingsController@index')->name('ico-ratings');
  Route::get('/search', 'SearchController@show')->name('search');
  Route::get('/search_ajax', 'SearchController@search_ajax')->name('search_ajax');
  Route::get('/crypto-wallets', 'WalletsController@index')->name('crypto-wallets');
  Route::get('/crypto-wallet/{id}', 'WalletsController@show')->name('crypto-wallet');
  Route::get('/ico-projects', 'ProjectsController@index')->name('ico-projects');
  Route::get('/ico-project/{id}', 'ProjectsController@show')->name('ico-project');
});

Route::group(['prefix' => 'invi', 'middleware' => ['auth']], function(){
  Route::get('/dashboard', 'invi\DashboardController@index')->name('invi_dashboard');
  Route::get('/filewizard', 'invi\FilewizardController@index')->name('filewizard');
  Route::resource('/locales', 'invi\LocalesController');
  Route::resource('/cryptocoins', 'invi\CryptocoinsController');
  Route::resource('/countries', 'invi\CountriesController');
  Route::resource('/substatus', 'invi\SubstatusController');
  Route::resource('/language', 'invi\LanguageController');
  Route::resource('/extra', 'invi\ExtraController');
  Route::resource('/status', 'invi\StatusController');
  Route::resource('/projects', 'invi\ProjectsController');
  Route::resource('/advert', 'invi\AdvContractsController');
  Route::resource('/categories', 'invi\CategoriesController');
  Route::resource('/platforms', 'invi\PlatformsController');
  Route::resource('/socials', 'invi\SocialsController');
  Route::resource('/invisocials', 'invi\InviSocialsController');
  Route::resource('/contentsettings', 'invi\ContentSettingsController');
  Route::resource('/invilinks', 'invi\InviLinksController');
  Route::resource('/os', 'invi\OSController');
  Route::resource('/agencies-rating', 'invi\AgenciesRatingController');
  Route::resource('/custom-rating', 'invi\CustomRatingController');
  Route::resource('/professions', 'invi\ProfessionsController');
  Route::resource('/advrequest', 'invi\AdvRequestController');
  Route::resource('/wallettype', 'invi\WalletTypeController');
  Route::resource('/wallets', 'invi\WalletsController');
  Route::resource('/type_tokens', 'invi\TypeTokenController');
  Route::resource('/tradings', 'invi\TradingController');
  Route::resource('/settings', 'invi\InviSetController');
  Route::resource('/ajax', 'invi\InviAjaxController');
  Route::resource('/project-filter', 'invi\ProjectFilterController');
  Route::resource('/wallet-filter', 'invi\WalletFilterController');
  Route::get('/advrequest-archive', 'invi\AdvRequestController@archive')->name('advrequest-archive');

});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::get('setlocale/{locale}','LocaleController@locale')->name('setlocale');
Route::post('/ajax/savecontracts','AjaxController@saveContracts');

Route::get('invilogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('invireg', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('invilogin', 'Auth\LoginController@login');
Route::post('invireg', 'Auth\RegisterController@register');
Route::post('invilogout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['locale']], function(){
  Route::get('/{url}', 'InviLinksController@show')->name('invilink');
});

app/Http/Controllers/invi/AdvContractsController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\AdvContracts;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class AdvContractsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.advert',[
        'contracts' => AdvContracts::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('invi.advert_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = AdvContracts::create($request->except(['_token', '_wysihtml5_mode']));
      return redirect()->route('advert.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('invi.advert_show',[
          'contract' => AdvContracts::where('id',$id)->first()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function edit(AdvContracts $advContracts)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AdvContracts $advContracts)
    {
      AdvContracts::where('id', $request->id)->update($request->except(['_method', '_token', '_wysihtml5_mode']));
      return redirect()->route('advert.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      AdvContracts::where('id', $id)->delete();
      return redirect()->route('advert.index');
    }
}

app/Http/Controllers/invi/AdvRequestController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\AdvRequest;

class AdvRequestController extends Controller
{
  public function index()
  {
    return view('invi.advrequests',[
      'advrequests' => AdvRequest::select()->where('is_archive','<>',1)->get()
    ]);
  }

  public function archive()
  {
    return view('invi.advrequests',[
      'advrequests' => AdvRequest::select()->where('is_archive',1)->get(),
      'archive' => true
    ]);
  }


  public function show($id)
  {
    return view('invi.advrequest',[
      'advrequest' => AdvRequest::where('id',$id)->first()
    ]);
  }

  public function update(Request $request, AdvRequest $advrequest)
  {
    AdvRequest::where('id', $request->id)->update($request->except(['_method', '_token']));
    return redirect()->route('advrequest.index');
  }


  public function destroy($id)
  {
    AdvRequest::where('id', $id)->delete();
    return redirect()->route('advrequest.index');
  }


}

app/Http/Controllers/invi/AgenciesRatingController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\AgenciesRating;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AgenciesRatingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.agencies-rating',[
        'agencies' => AgenciesRating::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = AgenciesRating::create($request->except(['_token']));
      return redirect()->route('agencies-rating.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.agency-rating',[
        'agency' => AgenciesRating::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function edit(AgenciesRating $agenciesRating)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AgenciesRating $agenciesRating)
    {
      AgenciesRating::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('agencies-rating.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      AgenciesRating::where('id', $id)->delete();
      return redirect()->route('agencies-rating.index');
    }
}

app/Http/Controllers/invi/CategoriesController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\Categories;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('invi.categories',[
          'categories' => Categories::select()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = Categories::create($request->except(['_token']));
      return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.category',[
        'category' => Categories::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(Categories $categories)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categories $categories)
    {
      Categories::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Categories::where('id', $id)->delete();
      return redirect()->route('categories.index');
    }
}

app/Http/Controllers/invi/ContentSettingsController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\ContentSettings;
use App\Models\Language;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContentSettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.contentsettings',[
        'contentsettings' => ContentSettings::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = ContentSettings::create($request->except(['_token']));
      return redirect()->route('contentsettings.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.contentsetting',[
        'contentsetting' => ContentSettings::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function edit(Language $language)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Language $language)
    {
        ContentSettings::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('contentsettings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      ContentSettings::where('id', $id)->delete();
      return redirect()->route('contentsettings.index');
    }
}

app/Http/Controllers/invi/CountriesController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\Countries;
use App\Models\Locales;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CountriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.countries',[
        'countries' => Countries::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = Countries::create($request->except(['_token']));
      return redirect()->route('countries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.country',[
        'country' => Countries::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function edit(Countries $countries)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Countries $countries)
    {
      Countries::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('countries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Countries::where('id', $id)->delete();
      return redirect()->route('countries.index');
    }
}

app/Http/Controllers/invi/DashboardController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{

  public function index()
  {
    return view('invi.dashboard');
  }




}

app/Http/Controllers/invi/FilewizardController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FilewizardController extends Controller
{
  public function index()
  {
    return view('invi.filewizard');
  }
}

resources/views/invi/advrequest.blade.php
@extends('invi.layouts.app')
@section('title','inviadmin - Заявка - '.$advrequest->name)
@section('description','inviadmin - Заявка - '.$advrequest->name)
@section('content')
<div class="content-wrapper">
  @component('invi.components.breadcrumb')
    @slot('title') Заявка - {{$advrequest->name}} @endslot
    @slot('parent') Заявки @endslot
    @slot('parent_link') {{route('advrequest.index')}} @endslot
    @slot('active') Заявка - {{$advrequest->name}} @endslot
  @endcomponent
  <section class="content">
    <form method="post" action="{{route('advrequest.update',$advrequest)}}">
      <input type="hidden" name="_method" value="put">
      <input type="hidden" name="id" value="{{$advrequest->id}}">
      {{csrf_field()}}
      <div class="row">
        <div class="col-6">
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Данные заявки</h3>
            </div>
            <div class="box-body">
              <div class="form-group">
                <h5>Имя</h5>
                <div class="controls">
                  <span>{{ $advrequest->name }}</span>
                </div>
              </div>
              <div class="form-group">
                <h5>Телефон</h5>
                <div class="controls">
                  <span>{{ $advrequest->phone }}</span>
                </div>
              </div>
              <div class="form-group">
                <h5>E-mail</h5>
                <div class="controls">
                  <span>{{ $advrequest->email }}</span>
                </div>
              </div>
              <div class="form-group">
                <h5>Сообщение</h5>
                <div class="controls">
                  <span>{{ $advrequest->message }}</span>
                </div>
              </div>
              <div class="form-group">
                <h5>Добавить комментарий</h5>
                <div class="controls">
                  <textarea name="comment" class="form-control" rows="6">{{ $advrequest->comment }}</textarea>
                </div>
              </div>
              <div class="form-group">
                <h5>Архивировать?</h5>
                <div class="controls">
                  <input type="radio" id="is_archive1" name="is_archive" value="1" @if($advrequest->is_archive == 1) checked @endif>
                  <label for="is_archive1">Да</label>
                  <input type="radio" id="is_archive0" name="is_archive" value="0" @if($advrequest->is_archive == 0) checked @endif>
                  <label for="is_archive0">Нет</label>
                </div>
              </div>
              <button type="submit" class="btn btn-success">Обновить заявку</button>
              <button type="button" class="btn btn-danger" onclick="event.preventDefault();document.getElementById('delete').submit();">Удалить</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
</div>
<form id="delete" action="{{ route('advrequest.destroy',$advrequest->id) }}" method="POST" style="display: none;">
  <input type="hidden" name="_method" value="delete">
  @csrf
</form>


@endsection

resources/views/invi/agency-rating.blade.php
@extends('invi.layouts.app')
@section('title','inviadmin - '.$agency->name)
@section('description','inviadmin - Агенты '.$agency->name)
@section('content')
<div class="content-wrapper">
  @component('invi.components.breadcrumb')
    @slot('title') {{$agency->name}} @endslot
    @slot('parent') Агенты @endslot
    @slot('parent_link') {{route('agencies-rating.index')}} @endslot
    @slot('active') {{$agency->name}} @endslot
  @endcomponent
  <section class="content">
      <div class="row">
        <div class="col-lg-6 col-12">
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Агенты</h3>
            </div>
            <div class="box-body">
              <form method="post" action="{{route('agencies-rating.update', $agency)}}">
                <input type="hidden" name="_method" value="put">
                <input type="hidden" name="id" value="{{$agency->id}}">
                {{csrf_field()}}
                <div class="form-group">
                  <h5>Название <span class="text-danger">*</span></h5>
                  <div class="controls">
                    <input type="text" name="name" class="form-control" required=""  value="{{$agency->name}}">
                  </div>
                </div>
                <div class="form-group">
                  <h5>Ссылка <span class="text-danger">*</span></h5>
                  <div class="controls">
                    <input type="url" name="url" class="form-control" required=""  value="{{$agency->url}}">
                  </div>
                </div>
                <div class="form-group">
                  <h5>Основной?</h5>
                  <div class="controls">
                    <input type="radio" id="is_main1" name="is_main" value="1" @if($agency->is_main == 1) checked @endif>
                    <label for="is_main1">Да</label>
                    <input type="radio" id="is_main0" name="is_main" value="0" @if($agency->is_main == 0) checked @endif>
                    <label for="is_main0">Нет</label>
                  </div>
                </div>
                <button type="submit" class="btn btn-success">Сохранить</button>
                <button type="button" class="btn btn-danger" onclick="event.preventDefault();document.getElementById('delete').submit();">Удалить</button>
              </form>
            </div>
          </div>
        </div>
    </div>
  </section>
</div>



<form id="delete" action="{{ route('agencies-rating.destroy',$agency->id) }}" method="POST" style="display: none;">
  <input type="hidden" name="_method" value="delete">
  @csrf
</form>

@endsection

resources/views/invi/project_filter.blade.php
@extends('invi.layouts.app')
@section('title','inviadmin - '.$project_filter->name_ru)
@section('description','inviadmin - Extra '.$project_filter->name_ru)
@section('content')
<div class="content-wrapper">
  @component('invi.components.breadcrumb')
    @slot('title') {{$project_filter->name_ru}} @endslot
    @slot('parent') Параметр проекта @endslot
    @slot('parent_link') {{route('project-filter.index')}} @endslot
    @slot('active') {{$project_filter->name_ru}} @endslot
  @endcomponent
  <section class="content">
      <div class="row">
        <div class="col-lg-12">
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Параметр фильтра проекта</h3>
            </div>
            <div class="box-body">
              <form method="post" action="{{route('project-filter.update', $project_filter)}}">
                <input type="hidden" name="_method" value="put">
                <input type="hidden" name="id" value="{{$project_filter->id}}">
                {{csrf_field()}}
                <div class="row">
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Название РУ<span class="text-danger">*</span></h5>
                      <div class="controls">
                        <input type="text" name="name_ru" class="form-control" required=""  value="{{$project_filter->name_ru}}">
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Название EN<span class="text-danger">*</span></h5>
                      <div class="controls">
                        <input type="text" name="name_en" class="form-control" required=""  value="{{$project_filter->name_en}}">
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Приоритет</h5>
                      <div class="controls">
                        <input type="text" name="priority" class="form-control" value="{{$project_filter->priority}}">
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Отображать как</h5>
                      <div class="controls">
                        <select name="type" class="form-control" id="type_list" @if($project_filter->is_system) disabled @endif>
                          <option value="multiselect" @if($project_filter->type == 'multiselect') selected @endif>Список</option>
                          <option value="onecheckbox" @if($project_filter->type == 'onecheckbox') selected @endif>Галочка</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row with-border">
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Отображать в фильтре?</h5>
                      <div class="controls">
                        <input type="radio" id="is_visible1" name="is_visible" value="1" @if($project_filter->is_visible == 1) checked @endif>
                        <label for="is_visible1">Да</label>
                        <input type="radio" id="is_visible0" name="is_visible" value="0" @if($project_filter->is_visible == 0) checked @endif>
                        <label for="is_visible0">Нет</label>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group">
                      <h5>Отображать название a фильтре?</h5>
                      <div class="controls">
                        <input type="radio" id="is_visible_name1" name="is_visible_name" value="1" @if($project_filter->is_visible_name == 1) checked @endif>
                        <label for="is_visible_name1">Да</label>
                        <input type="radio" id="is_visible_name0" name="is_visible_name" value="0" @if($project_filter->is_visible_name == 0) checked @endif>
                        <label for="is_visible_name0">Нет</label>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="box-header with-border">
                  <h3 class="box-title">Список значений</h3>
                </div>
                <div id="project-filter-wrap">
                @if (!($project_filter->is_system))
                    @forelse($project_filter->values as $i=>$project_filter_value)
                      <div class="project-filter-item row" data-index="{{$i}}">
                        <input type="hidden" name="project_values[{{$i}}][id]" value="{{$project_filter_value->id}}">
                        <div class="col-lg-5">
                          <div class="form-group">
                            <h5>Название РУ<span class="text-danger">*</span></h5>
                            <div class="controls">
                              <input type="text" name="project_values[{{$i}}][name_ru]" class="form-control" required=""  value="{{$project_filter_value->name_ru}}">
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-5">
                          <div class="form-group">
                            <h5>Название EN<span class="text-danger">*</span></h5>
                            <div class="controls">
                              <input type="text" name="project_values[{{$i}}][name_en]" class="form-control" required=""  value="{{$project_filter_value->name_en}}">
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-1">
                          <h5>Удаление</h5>
                          <button type="button" class="btn btn-danger delete-project-filter-value" id="remove_project_filter_value">Удалить элемент</button>
                        </div>
                      </div>
                    @empty
                      <div class="project-filter-item row" data-index="0">
                        <input type="hidden" name="project_values[0][id]" value="">
                        <div class="col-lg-5">
                          <div class="form-group">
                            <h5>Название РУ<span class="text-danger">*</span></h5>
                            <div class="controls">
                              <input type="text" name="project_values[0][name_ru]" class="form-control" required=""  value="">
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-5">
                          <div class="form-group">
                            <h5>Название EN<span class="text-danger">*</span></h5>
                            <div class="controls">
                              <input type="text" name="project_values[0][name_en]" class="form-control" required=""  value="">
                            </div>
                          </div>
                        </div>
                      </div>
                    @endforelse
                 </div>
                <div class="row">
                  <div class="col-lg-1"><button type="button" class="btn btn-info float-left" id="add_project_filter_item"><i class="fa fa-plus"></i></button></div>
                </div>
                  <hr/>
                 @endif
                <div class="row">
                  <div class="col-lg-12">
                  <button type="submit" class="btn btn-success">Сохранить</button>
                  @if(!($project_filter->is_system))
                  <button type="button" class="btn btn-danger" onclick="dropElement();">Удалить параметр</button>
                  @endif
                    </div>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </section>
</div>



<form id="delete" action="{{ route('project-filter.destroy',$project_filter->id) }}" method="POST" style="display: none;">
  <input type="hidden" name="_method" value="delete">
  @csrf
</form>
<script src="{{ asset('invi/js/pages/project_create.js') }}?{{ time() }}"></script>
@endsection