routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['locale']], function(){
  Route::get('/', 'HomeController@index')->name('home');
  Route::get('/advertise', 'AdvertController@index')->name('advertise');
  Route::get('/metodology', 'MetodologyController@show')->name('metodology');
  Route::get('/ico-ratings', 'RatingsController@index')->name('ico-ratings');
  Route::get('/search', 'SearchController@show')->name('search');
  Route::get('/search_ajax', 'SearchController@search_ajax')->name('search_ajax');
  Route::get('/crypto-wallets', 'WalletsController@index')->name('crypto-wallets');
  Route::get('/crypto-wallet/{id}', 'WalletsController@show')->name('crypto-wallet');
  Route::get('/ico-projects', 'ProjectsController@index')->name('ico-projects');
  Route::get('/ico-project/{id}', 'ProjectsController@show')->name('ico-project');
});

Route::group(['prefix' => 'invi', 'middleware' => ['auth']], function(){
  Route::get('/dashboard', 'invi\DashboardController@index')->name('invi_dashboard');
  Route::get('/filewizard', 'invi\FilewizardController@index')->name('filewizard');
  Route::resource('/locales', 'invi\LocalesController');
  Route::resource('/cryptocoins', 'invi\CryptocoinsController');
  Route::resource('/countries', 'invi\CountriesController');
  Route::resource('/substatus', 'invi\SubstatusController');
  Route::resource('/language', 'invi\LanguageController');
  Route::resource('/extra', 'invi\ExtraController');
  Route::resource('/status', 'invi\StatusController');
  Route::resource('/projects', 'invi\ProjectsController');
  Route::resource('/advert', 'invi\AdvContractsController');
  Route::resource('/categories', 'invi\CategoriesController');
  Route::resource('/platforms', 'invi\PlatformsController');
  Route::resource('/socials', 'invi\SocialsController');
  Route::resource('/invisocials', 'invi\InviSocialsController');
  Route::resource('/contentsettings', 'invi\ContentSettingsController');
  Route::resource('/invilinks', 'invi\InviLinksController');
  Route::resource('/os', 'invi\OSController');
  Route::resource('/agencies-rating', 'invi\AgenciesRatingController');
  Route::resource('/custom-rating', 'invi\CustomRatingController');
  Route::resource('/professions', 'invi\ProfessionsController');
  Route::resource('/advrequest', 'invi\AdvRequestController');
  Route::resource('/wallettype', 'invi\WalletTypeController');
  Route::resource('/wallets', 'invi\WalletsController');
  Route::resource('/type_tokens', 'invi\TypeTokenController');
  Route::resource('/tradings', 'invi\TradingController');
  Route::resource('/settings', 'invi\InviSetController');
  Route::resource('/ajax', 'invi\InviAjaxController');
  Route::resource('/project-filter', 'invi\ProjectFilterController');
  Route::resource('/wallet-filter', 'invi\WalletFilterController');
  Route::get('/advrequest-archive', 'invi\AdvRequestController@archive')->name('advrequest-archive');

});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});


Route::get('setlocale/{locale}','LocaleController@locale')->name('setlocale');
Route::post('/ajax/savecontracts','AjaxController@saveContracts');

Route::get('invilogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('invireg', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('invilogin', 'Auth\LoginController@login');
Route::post('invireg', 'Auth\RegisterController@register');
Route::post('invilogout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['locale']], function(){
  Route::get('/{url}', 'InviLinksController@show')->name('invilink');
});

app/Http/Controllers/invi/AdvContractsController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\AdvContracts;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class AdvContractsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.advert',[
        'contracts' => AdvContracts::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('invi.advert_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = AdvContracts::create($request->except(['_token', '_wysihtml5_mode']));
      return redirect()->route('advert.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('invi.advert_show',[
          'contract' => AdvContracts::where('id',$id)->first()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function edit(AdvContracts $advContracts)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AdvContracts $advContracts)
    {
      AdvContracts::where('id', $request->id)->update($request->except(['_method', '_token', '_wysihtml5_mode']));
      return redirect()->route('advert.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AdvContracts  $advContracts
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      AdvContracts::where('id', $id)->delete();
      return redirect()->route('advert.index');
    }
}

app/Http/Controllers/invi/AdvRequestController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\AdvRequest;

class AdvRequestController extends Controller
{
  public function index()
  {
    return view('invi.advrequests',[
      'advrequests' => AdvRequest::select()->where('is_archive','<>',1)->get()
    ]);
  }

  public function archive()
  {
    return view('invi.advrequests',[
      'advrequests' => AdvRequest::select()->where('is_archive',1)->get(),
      'archive' => true
    ]);
  }


  public function show($id)
  {
    return view('invi.advrequest',[
      'advrequest' => AdvRequest::where('id',$id)->first()
    ]);
  }

  public function update(Request $request, AdvRequest $advrequest)
  {
    AdvRequest::where('id', $request->id)->update($request->except(['_method', '_token']));
    return redirect()->route('advrequest.index');
  }


  public function destroy($id)
  {
    AdvRequest::where('id', $id)->delete();
    return redirect()->route('advrequest.index');
  }


}

app/Http/Controllers/invi/AgenciesRatingController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\AgenciesRating;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AgenciesRatingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.agencies-rating',[
        'agencies' => AgenciesRating::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = AgenciesRating::create($request->except(['_token']));
      return redirect()->route('agencies-rating.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.agency-rating',[
        'agency' => AgenciesRating::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function edit(AgenciesRating $agenciesRating)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, AgenciesRating $agenciesRating)
    {
      AgenciesRating::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('agencies-rating.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\AgenciesRating  $agenciesRating
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      AgenciesRating::where('id', $id)->delete();
      return redirect()->route('agencies-rating.index');
    }
}

app/Http/Controllers/invi/CategoriesController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\Categories;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('invi.categories',[
          'categories' => Categories::select()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = Categories::create($request->except(['_token']));
      return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.category',[
        'category' => Categories::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(Categories $categories)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categories $categories)
    {
      Categories::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Categories::where('id', $id)->delete();
      return redirect()->route('categories.index');
    }
}

app/Http/Controllers/invi/ContentSettingsController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\ContentSettings;
use App\Models\Language;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContentSettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.contentsettings',[
        'contentsettings' => ContentSettings::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = ContentSettings::create($request->except(['_token']));
      return redirect()->route('contentsettings.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.contentsetting',[
        'contentsetting' => ContentSettings::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function edit(Language $language)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Language $language)
    {
        ContentSettings::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('contentsettings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      ContentSettings::where('id', $id)->delete();
      return redirect()->route('contentsettings.index');
    }
}

app/Http/Controllers/invi/CountriesController.php
<?php

namespace App\Http\Controllers\invi;

use App\Models\Countries;
use App\Models\Locales;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CountriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('invi.countries',[
        'countries' => Countries::select()->get()
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $result = Countries::create($request->except(['_token']));
      return redirect()->route('countries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      return view('invi.country',[
        'country' => Countries::where('id',$id)->first()
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function edit(Countries $countries)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Countries $countries)
    {
      Countries::where('id', $request->id)->update($request->except(['_method', '_token', 'id']));
      return redirect()->route('countries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Countries  $countries
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Countries::where('id', $id)->delete();
      return redirect()->route('countries.index');
    }
}

app/Http/Controllers/invi/DashboardController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{

  public function index()
  {
    return view('invi.dashboard');
  }




}

app/Http/Controllers/invi/FilewizardController.php
<?php

namespace App\Http\Controllers\invi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FilewizardController extends Controller
{
  public function index()
  {
    return view('invi.filewizard');
  }
}

resources/views/invi/layouts/app.blade.php
@include('invi.layouts.head')
<body class="hold-transition skin-blue sidebar-mini fixed">
@include('invi.layouts.menu')
@yield('content')
@include('invi.layouts.footer')
</body>
</html>

resources/views/invi/layouts/footer.blade.php
<footer class="main-footer">
  <div class="pull-right d-none d-sm-inline-block"></div>
  &copy; Все права защищены. Информация сайта защищена законом об авторских правах.
</footer>

resources/views/invi/layouts/head.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="@yield('description')">
    <meta name="author" content="invi">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{ asset('invi/favicon.ico') }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{ asset('invi/css/bootstrap.css') }}?{{ time() }}">
    <link rel="stylesheet" href="{{ asset('invi/css/export.css') }}?{{ time() }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('invi/css/bootstrap-extend.css') }}?{{ time() }}">
    <link rel="stylesheet" href="{{ asset('invi/css/admin_style.css') }}?{{ time() }}">
    <meta name="robots" content="noindex, nofollow"/>
    <script src="{{ asset('invi/js/jquery.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/popper.min.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/bootstrap.min.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/jquery.slimscroll.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/fastclick.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/jquery.dataTables.min.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/template.js') }}?{{ time() }}"></script>
    <script src="{{ asset('invi/js/script.js') }}?{{ time() }}"></script>
  </head>

resources/views/invi/layouts/menu.blade.php
<div class="wrapper">
  <header class="main-header">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </header>
  <aside class="main-sidebar">
    <section class="sidebar">
      <div class="user-panel">
        <div class="ulogo">
          <a href="{{route('invi_dashboard')}}">
            <img src="{{ asset('invi/img/logo.svg') }}" alt="">
          </a>
        </div>
        <div class="info">
          <p>{{ Auth::user()->email }}</p>
          <a href="{{ route('logout') }}" class="link" data-toggle="tooltip" title=""  onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i></a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </div>
      </div>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="nav-devider"></li>
        <li class="header nav-small-cap">МЕНЮ</li>
        <li class="{{ request()->is('/invi/dashboard') ? 'active' : '' }}">
          <a href="{{route('invi_dashboard')}}">
          <i class="fa fa-dashboard"></i> <span>Рабочий стол</span>
        </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>Справочники</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('categories.index')}}">Категории</a></li>
            <li><a href="{{route('platforms.index')}}">Платформы</a></li>
            <li><a href="{{route('cryptocoins.index')}}">Криптовалюты</a></li>
            <li><a href="{{route('countries.index')}}">Страны</a></li>
            <li><a href="{{route('status.index')}}">Статусы</a></li>
            <li><a href="{{route('language.index')}}">Языки</a></li>
            <li><a href="{{route('extra.index')}}">Extra</a></li>
            <li><a href="{{route('agencies-rating.index')}}">Рейтинговые агенты</a></li>
            <li><a href="{{route('custom-rating.index')}}">Доп рейтинги</a></li>
            <li><a href="{{route('professions.index')}}">Профессии</a></li>
            <li><a href="{{route('os.index')}}">ОС</a></li>
            <li><a href="{{route('wallettype.index')}}">Типы кошельков</a></li>
            <li><a href="{{route('socials.index')}}">Соц сети</a></li>
            <li><a href="{{route('type_tokens.index')}}">Типы токенов</a></li>
            <li><a href="{{route('tradings.index')}}">Биржи</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>Настройки сайта</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('invisocials.index')}}">Соц сети в шапке и футере</a></li>
            <li><a href="{{route('contentsettings.index')}}">Контентные блоки</a></li>
            <li><a href="{{route('invilinks.index')}}">Службные страницы</a></li>
            <li><a href="{{route('settings.index')}}">Параметры</a></li>
            <li><a href="{{route('project-filter.index')}}">Фильтр проектов</a></li>
            <li><a href="{{route('wallet-filter.index')}}">Фильтр кошельков</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-tags" aria-hidden="true"></i>
            <span>Реклама</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('advert.index')}}">Реклама</a></li>
            <li><a href="{{route('advrequest.index')}}">Заявки</a></li>
          </ul>
        </li>
        <li class="{{ request()->is('/invi/wallets') ? 'active' : '' }}">
          <a href="{{route('wallets.index')}}">
          <i class="fa fa-money" aria-hidden="true"></i> <span>Кошельки</span>
        </a>
        </li>
        <li class="{{ request()->is('/invi/projects') ? 'active' : '' }}">
          <a href="{{route('projects.index')}}">
          <i class="fa fa-folder-open" aria-hidden="true"></i> <span>Проекты</span>
        </a>
        </li>
      </ul>
    </section>
  </aside>